app {
  name = "Task Management App"
  version = "1.2.3"
  environment = "development"
}

httpServer {
  port = 8080
  system.port = 8085
  telemetry.logging.enabled = true
}

logging {
  levels {
    root: warn
    "com.altro": debug
    "org.xnio": info
  }
}
