app {
  name = "Task Management App"
  version = "1.2.3"
  environment = "development"
}

httpServer {
  publicApiPort = 8080
  metrics.prometheus.enabled = true
}

db {
  jdbcUrl = "jdbc:postgresql://localhost:5432/testdb"
  username = "postgres"
  password = "password"

  flyway {
    enabled = true
    cleanDisabled = false
  }

  telemetry {
    "user-repository" {
      logging {
        enabled = true
        logLevel = "DEBUG"
      }
      metrics {
        enabled = true
      }
    }
  }
}

resilient.retry."com.altro.servicekora.user.db.PostgresRetry" {
  delay = "100ms"
  attempts = 3
}

cache.caffeine."com.altro.servicekora.user.db.UserCache" {
  expireAfterWrite = "10m"
  maximumSize = 1000
}
