app {
  name = "Task Management App"
  version = "1.2.3"
  environment = "development"
}

httpServer {
  publicApiPort = 8080
  metrics.prometheus.enabled = true
  ioThreads = 4
  workerThreads = 16
  publicApi {
    bufferSize = 16384
    directBuffers = true
  }
}

jdbc {
  jdbcUrl = "jdbc:postgresql://localhost:5432/service_kora"
  schema = "custom"
  username = "service_kora"
  password = "1"
  poolName = "service_kora-pool"
}

flyway {
  enabled = true
  cleanDisabled = false
}

telemetry {
  "user.service.get" {
    logging {
      enabled = true
      logLevel = "DEBUG"
    }
    metrics {
      enabled = true
    }
  }
}

resilient.retry.postgres-retry {
  delay = "100ms"
  attempts = 3
}

cache {
  users {
    expireAfterWrite = "10m"
    maximumSize = 1000
  }
}

openapi {
  management {
    enabled = true
    files = ["src/main/resources/openapi.yaml"]
  }
}