plugins {
    id "java"
    id "org.springframework.boot" version "3.5.13"
//    id "org.jetbrains.kotlin.jvm" version "2.3.20"
//    id 'io.micronaut.application' version '4.5.0'
//    id 'io.micronaut.aot' version '4.5.0'
//    id 'io.micronaut.openapi' version '4.5.0'
//    id 'org.openapi.generator' version '7.12.0'
}

ext {

    ver = [
            kotlin    : "2.3.20",
            springBoot: '3.5.13',
            openapi   : '6.20.0',
    ]

    jreImage = 'bellsoft/liberica-openjre-alpine:25.0.2'
    jreImageNative = 'debian:stable-slim'
}

java {
    sourceCompatibility = JavaVersion.VERSION_25
    targetCompatibility = JavaVersion.VERSION_25
}

dependencies {

    annotationProcessor(
            platform("org.springframework.boot:spring-boot-dependencies:$ver.springBoot"),
            "org.springframework.boot:spring-boot-configuration-processor",
            "org.projectlombok:lombok",
    )

    compileOnly(
            "org.projectlombok:lombok",
    )

    implementation(
            platform("org.springframework.boot:spring-boot-dependencies:$ver.springBoot"),
            "org.springframework.boot:spring-boot-starter-aop",
            "org.springframework.boot:spring-boot-starter-web",
            "org.springframework.boot:spring-boot-starter-logging",
            "org.springframework.boot:spring-boot-starter-json",
            "org.springframework.boot:spring-boot-starter-validation",
            "org.springframework.boot:spring-boot-starter-actuator",
            "io.micrometer:micrometer-tracing",
            "io.micrometer:context-propagation",
            "ch.qos.logback:logback-classic",
    )
//    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8"

    testAnnotationProcessor(
            platform("org.springframework.boot:spring-boot-dependencies:$ver.springBoot"),
            "org.projectlombok:lombok",
    )

    testCompileOnly(
            "org.projectlombok:lombok",
    )

    testImplementation(
            "org.springframework.boot:spring-boot-starter-test",
            "io.projectreactor.netty:reactor-netty-http",
    )
}

//project.gradle.startParameter.excludedTaskNames.add("generateServerOpenApiModels")
//tasks.named("generateServerOpenApiApis") {
//    it.enabled = false
//}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.compilerArgs = [
            '-parameters',
            '-Xlint:unchecked',
            '-Xlint:deprecation'
    ]
    options.fork = true
//    options.forkOptions.jvmArgs += "-Dmicronaut.openapi.views.spec=swagger-ui.enabled=true,swagger-ui.js.url=/openapi/res/"
}

configurations.configureEach {
    resolutionStrategy {
        cacheDynamicVersionsFor 0, 'minutes'
        cacheChangingModulesFor 0, 'minutes'
    }
}
repositories {
    mavenCentral()
}

test {
    useJUnitPlatform() // Включает поддержку JUnit 5

    // Позволяет видеть вывод логов (log.info) прямо в консоли при запуске через Gradle
    testLogging {
        showStandardStreams = true
        showExceptions = true
        showStackTraces = true
    }
    outputs.upToDateWhen { false }

    // НАСТРОЙКИ ПАМЯТИ
    minHeapSize = "2g"       // Начальный размер кучи
    maxHeapSize = "4g"       // Максимальный размер кучи

    // Дополнительные JVM аргументы для производительности тестов
    jvmArgs([
            "-XX:MaxMetaspaceSize=512m",        // Размер для метаданных классов
            "-XX:+UseG1GC",                     // Современный сборщик мусора
            "-XX:+UseStringDeduplication",      // Экономия памяти на повторяющихся строках JSON
            "-Dfile.encoding=UTF-8"             // Корректная кодировка для логов
    ])
}
//kotlin {
//    jvmToolchain(25)
//}
