version: '5.1.3'
name: "victoria-metrics-full"

services:
  # Единое хранилище (Метрики + Трейсы)
  victoria-metrics:
    image: victoriametrics/victoria-metrics:v1.142.0
    container_name: victoria-metrics
    ports:
      - "8428:8428"
    volumes:
      - vm-data:/victoria-metrics-data
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--retentionPeriod=1"
      - "-opentelemetry.usePrometheusNaming=true"
      - "-promscrape.config=/etc/prometheus/prometheus.yml"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - vm-net

  # Нативный агент приема трейсов
  victoria-traces:
    image: victoriametrics/victoria-traces:v0.8.2
    container_name: victoria-traces
    ports:
      - "4317:4317"
      - "10428:10428" # Добавил порт для запросов Grafana
    volumes:
      - vmtrace-data:/vmtrace-data
    command:
      - "-storageDataPath=/vmtrace-data" # <-- Указываем путь к волюму
      - "--servicegraph.enableTask=true"
    depends_on:
      - victoria-metrics
    networks:
      - vm-net

  # Хранилище логов (VictoriaLogs)
  victoria-logs:
    image: victoriametrics/victoria-logs:v1.50.0
    container_name: victoria-logs
    ports:
      - "9428:9428"
    volumes:
      - vlogs-data:/vlogs-data
    command:
      - "-retentionPeriod=7d"
    networks:
      - vm-net

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.151.0
    container_name: otel-collector
    command: ["--config=/etc/otel-collector-config.yml"]
    volumes:
      - ./otel-collector-config.yml:/etc/otel-collector-config.yml
    ports:
      - "4318:4318" # Только HTTP-приемник
      - "8889:8889" # Порт для метрик графа
    networks:
      - vm-net
    depends_on:
      - victoria-logs
      - victoria-traces

  # Интерфейс
  grafana:
    image: grafana/grafana:13.0.1
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_INSTALL_PLUGINS=victoriametrics-metrics-datasource,victoriametrics-logs-datasource
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    depends_on:
      - victoria-metrics
    networks:
      - vm-net
    volumes:
      - grafana-storage:/var/lib/grafana

networks:
  vm-net:

volumes:
  vm-data:
  vlogs-data:
  vmtrace-data:
  grafana-storage:
