version: '5.1.3'

services:
  # Хранилище логов (Loki4j в приложении должен стучаться сюда на порт 3100)
  loki:
    image: grafana/loki:3.7.1
    ports:
      - "3100:3100"
    volumes:
      - ./loki-config.yml:/etc/loki/local-config.yaml # Пробрасываем наш файл
    command: -config.file=/etc/loki/local-config.yaml

  # Графический интерфейс
  grafana:
    image: grafana/grafana:13.0.1
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    depends_on:
      - loki
