FROM ubuntu:25.04

RUN apt update && apt upgrade -y
RUN apt update && apt install -y openjdk-17-jre ffmpeg

COPY build/libs/micronaut3-bug.jar app.jar

ENTRYPOINT ["java", "-Dfile.encoding=UTF-8", "-jar","/app.jar"]
