version: '5.1.3'

services:
  # Хранилище логов (Loki4j в приложении должен стучаться сюда на порт 3100)
  loki:
    image: grafana/loki:3.7.1
    ports:
      - "3100:3100"
    volumes:
      - ./loki-config.yml:/etc/loki/local-config.yaml # Пробрасываем наш файл
    command: -config.file=/etc/loki/local-config.yaml

  # Хранилище трейсов (Tempo)
  tempo:
    image: grafana/tempo:2.10.5
    command: [ "-config.file=/etc/tempo.yaml" ]
    environment:
      - TEMPO_ADVERTISE_ADDRESS=tempo
    volumes:
      - ./tempo-config.yml:/etc/tempo.yaml
    ports:
      - "3200:3200"   # Tempo UI/API
      - "4317:4317"   # OTLP gRPC (для экспорта)
      - "4318:4318"   # OTLP HTTP (наш случай для приложения)
      - "9095:9095"   # Добавь этот порт для внутреннего общения
    depends_on:
      - loki

  # Хранилище метрик (нужно для работы вкладки Traces и отрисовки графиков на основе трейсов)
  prometheus:
    image: prom/prometheus:v3.11.2
    container_name: prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --web.enable-remote-write-receiver
      - --enable-feature=exemplar-storage
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - tempo

  # Графический интерфейс
  grafana:
    image: grafana/grafana:13.0.1
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    depends_on:
      - loki
    volumes:
      - grafana-storage:/var/lib/grafana # <--- Сохранит все твои настройки и дашборды

volumes:
  grafana-storage:
