[package]
name = "my-llama"
version = "0.1.0"
edition = "2024"

[dependencies]
libc = "0.2"
base64 = "0.22"
safetensors = "0.8"
memmap2 = "0.9"

[build-dependencies]
cc = "1.2"

[lib]
name = "my_llama"
path = "src/lib.rs"

[[bin]]
name = "infer"
path = "src/bin/infer.rs"

[[bin]]
name = "train"
path = "src/bin/train.rs"