[package]
name = "my-llama"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
regex-automata = { version = "0.4", features = ["dfa-build", "dfa-search", "syntax", "unicode"] }

[build-dependencies]
cc = "1.2"

[dev-dependencies]
criterion = { version = "0.8", features = ["html_reports"] }

[lib]
name = "my_llama"
path = "src/lib.rs"

[[bin]]
name = "infer"
path = "src/bin/infer.rs"

[[bin]]
name = "train"
path = "src/bin/train.rs"

[[bin]]
name = "train_tokenizer"
path = "src/bin/train_tokenizer.rs"

[[bin]]
name = "load_tokenizer"
path = "src/bin/load_tokenizer.rs"

[[bin]]
name = "infer_simple"
path = "src/bin/infer_simple.rs"

#[[bench]]
#name = "tokenizer_benchmark"
#path = "tests/benches/tokenizer_benchmark.rs"
#harness = false

[[bench]]
name = "trainer_benchmark"
path = "tests/benches/trainer_bench.rs"
harness = false

[[test]]
name = "tokenizer_integration_tests"
path = "tests/tokenizer/tokenizer_integration_tests.rs"

[profile.release]
opt-level = 3
lto = "thin"
codegen-units = 16
panic = "abort"
strip = "symbols"

[profile.bench]
opt-level = 3
lto = "fat"
codegen-units = 16

[profile.dev]
opt-level = 1
debug = true
panic = "abort"
