
micronaut:
  server:
    port: 8080
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /openapi/**
  http:
    client:
      read-timeout: 5000s
    services:
      local:
        url: http://127.0.0.1:8080
      test:
        url: http://127.0.0.1:8080
  serde:
    jackson:
      parser-features:
        ALLOW_COMMENTS: false
      read-features:
        ALLOW_JAVA_COMMENTS: false
