server:
  port: 8080
  http2:
    enabled: true

spring:
  threads:
    virtual:
      enabled: true
  reactor:
    context-propagation: auto
  web:
    locale: en_US
    locale-resolver: fixed
  main:
    banner-mode: off
  http:
    codecs:
      max-in-memory-size: 10MB

logging:
  level:
    root: debug
    sun: info
    javax: info
    org.apache: info
