
micronaut:
  application:
    name: micronaut_bug
  server:
    port: 8080

flyway:
  datasources:
    default:
      baseline-on-migrate: true
      sql-migration-prefix: ''

logger:
  levels:
    root: INFO
