server:
  port: 8080
  forward-headers-strategy: native
  servlet:
    context-path:
    session:
      timeout: 60s
      cookie:
        name: JSESSIONUPDATER

spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  web:
    locale: en_US
    locale-resolver: fixed
  mvc:
    log-request-details: false
  main:
    banner-mode: off

management:
  endpoints:
    web:
      exposure:
        include: