server:
  port: 8080
  http2:
    enabled: true

spring:
  mandatory-file-encoding: UTF-8
  web:
    locale: en_US
    locale-resolver: fixed
  main:
    banner-mode: off
  http:
    codecs:
      max-in-memory-size: 10MB

logging:
  level:
    root: debug
    sun: info
    javax: info
    org.apache: info
