
micronaut:
  application:
    name: micronaut_bug
  server:
    port: 8080

jackson:
  property-naming-strategy: LOWER_CAMEL_CASE
  locale: en_US
  date-format: yyyy-MM-dd'T'HH:mm:ss.SSS
  mapper:
    ACCEPT_CASE_INSENSITIVE_ENUMS: true
  serialization:
    INDENT_OUTPUT: false
    WRITE_DATE_TIMESTAMPS_AS_NANOSECONDS: false
    WRITE_DATES_AS_TIMESTAMPS: false
  deserialization:
    FAIL_ON_UNKNOWN_PROPERTIES: false
    READ_DATE_TIMESTAMPS_AS_NANOSECONDS: false
  serialization-inclusion: non_null

flyway:
  datasources:
    default:
      baseline-on-migrate: true
      sql-migration-prefix: ''

logger:
  levels:
    root: INFO
