app:
  node:
    name: ift2
  log:
    pattern:
      console: "%d{HH:mm:ss.SSS} %highlight(%-5level) %magenta(%mdcBlock)[%thread] %cyan(%logger{25}) - %msg%n%throwable"
    mdc-keys: test
    pretty-print: true
    max-payload-size: 4MB
  integration:
    ext-service:
      endpoints:
        ping:
          path: /health/check
          method: GET
          with-api-key: false
        process-file:
          path: /v1/files/upload
          method: POST
        update-data:
          path: /v1/data/sync
          method: POST
        complex-multipart:
          path: /v2/complex-process/{id}
          method: POST
      http:
        url: http://localhost:8081
        compress: true
        log:
          pretty-print: true
          max-payload-size: 4MB

server:
  port: 8080

spring:
  application:
    name: spring-log
  servlet:
    multipart:
      enabled: true
  web:
    locale: en_US
    locale-resolver: fixed
  main:
    banner-mode: off
  http:
    codecs:
      max-in-memory-size: 10MB

logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} %highlight(%-5level) [%thread] %cyan(%logger{25}) - %msg%n%throwable"
  level:
    root: debug
    jdk: info
    sun: info
    javax: info
    io.netty: info
    org.apache: info
    org.eclipse: info
    org.hibernate: info
    org.springframework: info
#    reactor.netty.http.server.HttpServer: DEBUG
    reactor: info
