server:
  port: 8080
  tomcat:
    accept-count: 10000  # Увеличиваем очередь сокетов на уровне ОС
    max-connections: 10000 # Максимум открытых соединений
  http2:
    enabled: true

spring:
  servlet:
    multipart:
      enabled: true
#  threads:
#    virtual:
#      enabled: true
  web:
    locale: en_US
    locale-resolver: fixed
  main:
    banner-mode: off
  http:
    codecs:
      max-in-memory-size: 10MB

logging:
  level:
    root: debug
    sun: info
    javax: info
    org.apache: info
    org.hibernate: info
    org.springframework: info
