server:
  port: 8080
  forward-headers-strategy: native
  servlet:
    context-path:
    session:
      timeout: 60s
      cookie:
        name: JSESSIONUPDATER

spring:
  application:
    name: updater
  mandatory-file-encoding: UTF-8
  web:
    locale: en_US
    locale-resolver: fixed
  mvc:
    log-request-details: false
  main:
    banner-mode: off
