[versions]
spring = "4.1.0-RC1"
spring-ai = "2.0.0-M7"
kotlin = "2.3.21"
coroutines = "1.11.0"
kotlin-log = "8.0.03"
protobuf = "4.35.0"
otel-proto = "1.10.0-alpha"
wiremock = "3.13.2"
disruptor = "4.0.0"

jmh = "0.7.3"
jib = "3.5.3"

[libraries]
kotlin-logging = { module = "io.github.oshai:kotlin-logging-jvm", version.ref = "kotlin-log" }
protobuf-java = { module = "com.google.protobuf:protobuf-java", version.ref = "protobuf" }
otel-proto = { module = "io.opentelemetry.proto:opentelemetry-proto", version.ref = "otel-proto" }
wiremock = { module = "org.wiremock:wiremock-standalone", version.ref = "wiremock" }
disruptor = { module = "com.lmax:disruptor", version.ref = "disruptor" }

# BOMs
spring-boot-dependencies = { module = "org.springframework.boot:spring-boot-dependencies", version.ref = "spring" }
kotlin = { module = "org.jetbrains.kotlin:kotlin-bom", version.ref = "kotlin" }
coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-bom", version.ref = "coroutines" }
spring-ai = { module = "org.springframework.ai:spring-ai-bom", version.ref = "spring-ai" }

[plugins]
spring-boot = { id = "org.springframework.boot", version.ref = "spring" }
spring-boot-aot = { id = "org.springframework.boot.aot", version.ref = "spring" }
jib = { id = "com.google.cloud.tools.jib", version.ref = "jib" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
jmh = { id = "me.champeau.jmh", version.ref = "jmh" }
