/*
 * Compute API
 * API for the Compute Service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.micronaut.bug.api;

import java.util.Objects;

import io.micronaut.core.annotation.Introspected;
import io.micronaut.serde.annotation.Serdeable;
import io.swagger.v3.oas.annotations.media.Schema;

import jakarta.validation.constraints.NotNull;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * Mammal
 */
@Serdeable
@JsonPropertyOrder({
    Mammal.JSON_PROPERTY_WEIGHT,
    Mammal.JSON_PROPERTY_DESCRIPTION
})
public class Mammal extends Animal {

    public static final String JSON_PROPERTY_WEIGHT = "weight";
    public static final String JSON_PROPERTY_DESCRIPTION = "description";

    @NotNull
    @Schema(name = "weight", requiredMode = Schema.RequiredMode.REQUIRED)
    @JsonProperty(JSON_PROPERTY_WEIGHT)
    private Float weight;

    @NotNull
    @Schema(name = "description", requiredMode = Schema.RequiredMode.REQUIRED)
    @JsonProperty(JSON_PROPERTY_DESCRIPTION)
    private String description;

    private Mammal() {
    }

    public Mammal(Float weight, String description) {
        this.weight = weight;
        this.description = description;
    }

    /**
     * @return the weight property value
     */
    public Float getWeight() {
        return weight;
    }

    /**
     * Set the weight property value
     */
    public void setWeight(Float weight) {
        this.weight = weight;
    }

    /**
     * Set weight in a chainable fashion.
     *
     * @return The same instance of Mammal for chaining.
     */
    public Mammal weight(Float weight) {
        this.weight = weight;
        return this;
    }

    /**
     * @return the description property value
     */
    public String getDescription() {
        return description;
    }

    /**
     * Set the description property value
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * Set description in a chainable fashion.
     *
     * @return The same instance of Mammal for chaining.
     */
    public Mammal description(String description) {
        this.description = description;
        return this;
    }

    @Override
    public Mammal propertyClass(String propertyClass) {
        super.setPropertyClass(propertyClass);
        return this;
    }

    @Override
    public Mammal color(ColorEnum color) {
        super.setColor(color);
        return this;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Mammal mammal = (Mammal) o;
        return Objects.equals(weight, mammal.weight) &&
            Objects.equals(description, mammal.description) &&
            super.equals(o);
    }

    @Override
    public int hashCode() {
        return Objects.hash(weight, description, super.hashCode());
    }

    @Override
    public String toString() {
        return "Mammal("
            + "propertyClass: " + getPropertyClass() + ", "
            + "color: " + getColor()
            + ")";
    }

}
