package com.micronaut.bug.trace.jdbc

import com.micronaut.bug.trace.NanoTracer
import com.micronaut.bug.trace.config.TraceProperties.TraceJdbcProperties
import com.micronaut.bug.trace.jdbc.JdbcUrlParser.ConnectionInfo
import java.sql.CallableStatement
import java.sql.Connection
import java.sql.PreparedStatement
import java.sql.Statement

@Suppress("JavaDefaultMethodsNotOverriddenByDelegation", "SqlSourceToSinkFlow")
class TraceConnection(
    private val delegate: Connection,
    private val tracer: NanoTracer,
    private val traceProps: TraceJdbcProperties,
    private val connectionInfo: ConnectionInfo,
) : Connection by delegate {

    override fun prepareStatement(sql: String): PreparedStatement =
        TracePreparedStatement(delegate.prepareStatement(sql), sql, tracer, traceProps, connectionInfo)

    override fun prepareStatement(sql: String, autoGeneratedKeys: Int): PreparedStatement =
        TracePreparedStatement(delegate.prepareStatement(sql, autoGeneratedKeys), sql, tracer, traceProps, connectionInfo)

    override fun prepareStatement(sql: String, columnIndexes: IntArray?): PreparedStatement =
        TracePreparedStatement(delegate.prepareStatement(sql, columnIndexes), sql, tracer, traceProps, connectionInfo)

    override fun prepareStatement(sql: String, columnNames: Array<out String>?): PreparedStatement =
        TracePreparedStatement(delegate.prepareStatement(sql, columnNames), sql, tracer, traceProps, connectionInfo)

    override fun prepareStatement(sql: String, resultSetType: Int, resultSetConcurrency: Int): PreparedStatement =
        TracePreparedStatement(delegate.prepareStatement(sql, resultSetType, resultSetConcurrency), sql, tracer, traceProps, connectionInfo)

    override fun prepareStatement(sql: String, resultSetType: Int, resultSetConcurrency: Int, resultSetHoldability: Int): PreparedStatement =
        TracePreparedStatement(delegate.prepareStatement(sql, resultSetType, resultSetConcurrency, resultSetHoldability), sql, tracer, traceProps, connectionInfo)

    override fun createStatement(): Statement =
        TraceStatement(delegate.createStatement(), tracer, traceProps, connectionInfo)

    override fun createStatement(resultSetType: Int, resultSetConcurrency: Int): Statement =
        TraceStatement(delegate.createStatement(resultSetType, resultSetConcurrency), tracer, traceProps, connectionInfo)

    override fun createStatement(resultSetType: Int, resultSetConcurrency: Int, resultSetHoldability: Int): Statement =
        TraceStatement(delegate.createStatement(resultSetType, resultSetConcurrency, resultSetHoldability), tracer, traceProps, connectionInfo)

    override fun prepareCall(sql: String): CallableStatement =
        TraceCallableStatement(delegate.prepareCall(sql), sql, tracer, traceProps, connectionInfo)

    override fun prepareCall(sql: String, resultSetType: Int, resultSetConcurrency: Int): CallableStatement =
        TraceCallableStatement(delegate.prepareCall(sql, resultSetType, resultSetConcurrency), sql, tracer, traceProps, connectionInfo)

    override fun prepareCall(sql: String, resultSetType: Int, resultSetConcurrency: Int, resultSetHoldability: Int): CallableStatement =
        TraceCallableStatement(delegate.prepareCall(sql, resultSetType, resultSetConcurrency, resultSetHoldability), sql, tracer, traceProps, connectionInfo)
}
