package com.micronaut.bug.trace.jdbc

import com.micronaut.bug.trace.NanoTracer
import com.micronaut.bug.trace.config.TraceProperties.TraceJdbcProperties
import java.sql.CallableStatement
import java.sql.ResultSet

@Suppress("JavaDefaultMethodsNotOverriddenByDelegation", "SqlSourceToSinkFlow")
class TraceCallableStatement(
    private val delegate: CallableStatement,
    private val sql: String,
    tracer: NanoTracer,
    traceProps: TraceJdbcProperties
) : BaseTraceStatement(tracer, traceProps), CallableStatement by delegate {

    override fun execute(): Boolean =
        executeWithTrace(sql) { delegate.execute() }

    override fun executeQuery(): ResultSet =
        executeWithTrace(sql) { delegate.executeQuery() }

    override fun executeUpdate(): Int =
        executeWithTrace(sql) { delegate.executeUpdate() }

    override fun execute(sql: String): Boolean =
        executeWithTrace(sql) { delegate.execute(sql) }

    override fun execute(sql: String, autoGeneratedKeys: Int): Boolean =
        executeWithTrace(sql) { delegate.execute(sql, autoGeneratedKeys) }

    override fun execute(sql: String, columnIndexes: IntArray?): Boolean =
        executeWithTrace(sql) { delegate.execute(sql, columnIndexes) }

    override fun execute(sql: String, columnNames: Array<out String>?): Boolean =
        executeWithTrace(sql) { delegate.execute(sql, columnNames) }

    override fun executeQuery(sql: String): ResultSet =
        executeWithTrace(sql) { delegate.executeQuery(sql) }

    override fun executeUpdate(sql: String): Int =
        executeWithTrace(sql) { delegate.executeUpdate(sql) }

    override fun executeUpdate(sql: String, autoGeneratedKeys: Int): Int =
        executeWithTrace(sql) { delegate.executeUpdate(sql, autoGeneratedKeys) }

    override fun executeUpdate(sql: String, columnIndexes: IntArray?): Int =
        executeWithTrace(sql) { delegate.executeUpdate(sql, columnIndexes) }

    override fun executeUpdate(sql: String, columnNames: Array<out String>?): Int =
        executeWithTrace(sql) { delegate.executeUpdate(sql, columnNames) }
}
