app:
  wiremock:
    enabled: true
    port: 8083
  log:
    enabled: false
  trace:
    enabled: false

server:
  port: 8082
  tomcat:
    additional-tld-skip-patterns: "*"

spring:
  application:
    name: mock-server
  servlet:
    multipart:
      enabled: true
  web:
    locale: en_US
    locale-resolver: fixed
    resources:
      add-mappings: false
  main:
    banner-mode: off

logging:
  pattern:
    console: "%d{MM-dd HH:mm:ss.SSS} %highlight{%level} %style{%uMDC}{magenta} [%t] %style{%logger{1.}}{cyan} : %msg%n%uEx"
  level:
    root: debug
    jdk: warn
    sun: warn
    javax: info
    io.netty: info
    com.zaxxer: warn
    org.apache: warn
    org.flywaydb: info
    liquibase: info
    io.micrometer: info
    org.postgresql: info
    org.eclipse: info
    org.hibernate: info
    org.springframework: info
    #    reactor.netty.http.server.HttpServer: DEBUG
    reactor: info
