package com.altro.common.trace.jdbc

import com.altro.common.trace.NanoTracer
import com.altro.common.trace.config.TraceProperties.TraceJdbcProperties
import com.altro.common.trace.jdbc.JdbcUrlParser.ConnectionInfo
import java.sql.ResultSet
import java.sql.Statement

@Suppress("JavaDefaultMethodsNotOverriddenByDelegation", "SqlSourceToSinkFlow")
class TraceStatement(
    private val delegate: Statement,
    tracer: NanoTracer,
    traceProps: TraceJdbcProperties,
    connectionInfo: ConnectionInfo,
) : BaseTraceStatement(tracer, traceProps, connectionInfo), Statement by delegate {

    override fun execute(sql: String): Boolean =
        executeWithTrace(sql) { delegate.execute(sql) }

    override fun execute(sql: String, autoGeneratedKeys: Int): Boolean =
        executeWithTrace(sql) { delegate.execute(sql, autoGeneratedKeys) }

    override fun execute(sql: String, columnIndexes: IntArray?): Boolean =
        executeWithTrace(sql) { delegate.execute(sql, columnIndexes) }

    override fun execute(sql: String, columnNames: Array<out String>?): Boolean =
        executeWithTrace(sql) { delegate.execute(sql, columnNames) }

    override fun executeQuery(sql: String): ResultSet =
        executeWithTrace(sql) { delegate.executeQuery(sql) }

    override fun executeUpdate(sql: String): Int =
        executeWithTrace(sql) { delegate.executeUpdate(sql) }

    override fun executeUpdate(sql: String, autoGeneratedKeys: Int): Int =
        executeWithTrace(sql) { delegate.executeUpdate(sql, autoGeneratedKeys) }

    override fun executeUpdate(sql: String, columnIndexes: IntArray?): Int =
        executeWithTrace(sql) { delegate.executeUpdate(sql, columnIndexes) }

    override fun executeUpdate(sql: String, columnNames: Array<out String>?): Int =
        executeWithTrace(sql) { delegate.executeUpdate(sql, columnNames) }

    override fun executeLargeUpdate(sql: String): Long =
        executeWithTrace(sql) { delegate.executeLargeUpdate(sql) }

    override fun executeLargeUpdate(sql: String, autoGeneratedKeys: Int): Long =
        executeWithTrace(sql) { delegate.executeLargeUpdate(sql, autoGeneratedKeys) }

    override fun executeLargeUpdate(sql: String, columnIndexes: IntArray?): Long =
        executeWithTrace(sql) { delegate.executeLargeUpdate(sql, columnIndexes) }

    override fun executeLargeUpdate(sql: String, columnNames: Array<out String>?): Long =
        executeWithTrace(sql) { delegate.executeLargeUpdate(sql, columnNames) }

    override fun executeBatch(): IntArray =
        executeBatchWithTrace(null) { delegate.executeBatch() }

    override fun executeLargeBatch(): LongArray =
        executeBatchWithTrace(null) { delegate.executeLargeBatch() }
}
