app:
  node:
    name: ift2
  trace:
    enabled: true
    export:
      enabled: true
      url: http://localhost:4318/v1/traces
      # Напрямую в викторию
      #url: http://localhost:10428/insert/opentelemetry/v1/traces
      connect-timeout: 2s
    http:
      enabled: true
    jdbc:
      enabled: true
  log:
    enabled: true
    mdc-keys: test
    pretty-print: true
    max-payload-size: 4MB
    export:
      enabled: true
      url: http://localhost:4318/v1/logs
      # Напрямую в викторию
      # url: http://localhost:9428/insert/opentelemetry/v1/logs
  integration:
    ext-service:
      endpoints:
        update-data:
          path: /testtracelog/v1/data/sync
          method: POST
      http:
        service-name: ext-service
        url: http://localhost:8083
        type: external
        compress: true
        log:
          pretty-print: true
          max-payload-size: 4MB

server:
  port: 8081
  tomcat:
    additional-tld-skip-patterns: "*"

spring:
  application:
    name: service1
  servlet:
    multipart:
      enabled: true
  web:
    locale: en_US
    locale-resolver: fixed
    resources:
      add-mappings: false
  main:
    banner-mode: off

management:
  server:
    port: 9081
  observations:
    key-values:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
  metrics:
    distribution:
      percentiles-histogram:
        all: true
    enable:
      all: true
  otlp:
    metrics:
      export:
        enabled: false
        #url: http://localhost:8428/opentelemetry/v1/metrics
        url: http://localhost:4318/v1/metrics
        step: PT10S
        aggregation-temporality: delta
        headers:
          Content-Type: application/x-protobuf
        resource-attributes:
          "service.name": ${spring.application.name}
          "deployment.environment": ${app.node.name}
logging:
  pattern:
    console: "%d{MM-dd HH:mm:ss.SSS} %highlight{%level} %style{%uMDC}{magenta} [%t] %style{%logger{1.}}{cyan} : %msg%n%uEx"
  level:
    root: debug
    jdk: warn
    sun: warn
    javax: info
    io.netty: info
    com.zaxxer: warn
    org.apache: warn
    org.flywaydb: info
    liquibase: info
    io.micrometer: info
    org.postgresql: info
    org.eclipse: info
    org.hibernate: info
    org.springframework: info
    #    reactor.netty.http.server.HttpServer: DEBUG
    reactor: info
