/*
 * Compute API
 * API for the Compute Service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.micronaut.bug.api

import com.micronaut.bug.api.Animal
import com.micronaut.bug.api.ColorEnum
import com.fasterxml.jackson.annotation.*
import io.micronaut.serde.annotation.Serdeable
import jakarta.validation.constraints.*
import jakarta.validation.Valid
import io.micronaut.core.annotation.Nullable
import jakarta.annotation.Generated
import io.swagger.v3.oas.annotations.media.Schema

/**
 * Mammal
 *
 * @param weight
 * @param description
 */
@Serdeable
@JsonPropertyOrder(
        Mammal.JSON_PROPERTY_WEIGHT,
        Mammal.JSON_PROPERTY_DESCRIPTION
)
@Generated("io.micronaut.openapi.generator.KotlinMicronautServerCodegen")
data class Mammal (
    @NotNull
    @Schema(name = "weight", requiredMode = Schema.RequiredMode.REQUIRED)
    @JsonProperty(JSON_PROPERTY_WEIGHT)
    var weight: Float,
    @NotNull
    @Schema(name = "description", requiredMode = Schema.RequiredMode.REQUIRED)
    @JsonProperty(JSON_PROPERTY_DESCRIPTION)
    var description: String,
): Animal()  {

    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (javaClass != other?.javaClass) return false
        if (!super.equals(other)) return false
        other as Mammal

        if (weight != other.weight) return false
        if (description != other.description) return false

        return true
    }

    override fun hashCode(): Int {
        var result = super.hashCode()
        result = 31 * result + weight.hashCode()
        result = 31 * result + description.hashCode()
        return result
    }

    override fun toString(): String {
        return "Mammal(weight='$weight', description='$description', propertyClass='$propertyClass', color='$color')"
    }

    companion object {

        const val JSON_PROPERTY_WEIGHT = "weight"
        const val JSON_PROPERTY_DESCRIPTION = "description"
    }
}
