/*
 * Compute API
 * API for the Compute Service
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.micronaut.bug.api

import com.fasterxml.jackson.annotation.JsonCreator
import com.fasterxml.jackson.annotation.JsonProperty
import com.fasterxml.jackson.annotation.JsonValue
import io.micronaut.serde.annotation.Serdeable

/**
 * Gets or Sets ColorEnum
 *
 * @param value The value represented by this enum
 */
@Serdeable
enum class ColorEnum(
        @get:JsonValue val value: String
) {

    @JsonProperty("red")
    RED("red"),

    @JsonProperty("blue")
    BLUE("blue"),

    @JsonProperty("green")
    GREEN("green"),

    @JsonProperty("light-blue")
    LIGHT_BLUE("light-blue"),

    @JsonProperty("dark-green")
    DARK_GREEN("dark-green");

    override fun toString(): String {
        return value
    }

    companion object {

        @JvmField
        val VALUE_MAPPING = entries.associateBy { it.value }

        /**
         * Create this enum from a value.
         *
         * @param value value for enum
         *
         * @return The enum
         */
        @JsonCreator
        @JvmStatic
        fun fromValue(value: String): ColorEnum {
            require(VALUE_MAPPING.containsKey(value)) { "Unexpected value '$value'" }
            return VALUE_MAPPING[value]!!
        }
    }
}
